config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  do_not_validate_attachment_file_type :signature_img
  has_attached_file :signature_img, :default_url => ""
  has_attached_file :signature_blank, :default_url => ""

  validates :signature_img, presence: { message: 'Please enter valid signature on image' }
  validates :signature_blank, presence: { message: 'Please enter valid signature on blank' }

  before_save :set_file_name

  def set_file_name
    self.signature_img_file_name = "#{self.first_name}_sign_img"
    self.signature_blank_file_name = "#{self.first_name}_sign"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :signature)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :signatures, :signature_img, :signature_blank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :customer_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :customer_last_name %>
  </div>

  <div class="field">
    <%= form.label :signature %>
    <%= form.text_area :signature, id: :customer_signature %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.signature %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @customer.signature %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Signature</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'signature_pad.umd', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, id: "form", html: { multipart: true } ) do |form| %>
  <div class="field">
  <%= form.label :signature_blank %>
  <div class="wrapper-blank">
    <canvas id="signature-pad-blank" class="signature-pad-blank" width=300 height=200 ></canvas>
  </div>
  <h4 id="clear_blank">Clear</h4>
</div>
  <div class="field">
  <%= form.label :signature %>
  <div class="wrapper">
    <canvas id="signature-pad" class="signature-pad" ></canvas>
  </div>
  <h4 id="clear">Clear</h4>
</div>


<div class="field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, id: :user_first_name %>
</div>

<div class="field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, id: :user_last_name %>
  <%= form.hidden_field :signatures, id: :user_signature %>
  <%= form.hidden_field :signature_img, id: :signature_img %>
  <%= form.hidden_field :signature_blank, id: :signature_blank %>
</div>

<h4 id="save">Save</h4>
<% end %>


<script>

var canvas = document.getElementById('signature-pad');
ctx = canvas.getContext("2d");
var background = new Image();
background.src = "http://localhost:3000/van_picture.jpg";
background.onload = function() {
  canvas.width = background.naturalWidth
    canvas.height = background.naturalHeight
    ctx.drawImage(background, 0, 0);
};
function resizeCanvas() {
  var ratio =  Math.max(window.devicePixelRatio || 1, 1);
  canvas.width = canvas.offsetWidth * ratio;
  canvas.height = canvas.offsetHeight * ratio;
  canvas.getContext("2d").scale(ratio, ratio);
}
window.onresize = resizeCanvas;
resizeCanvas();

var signaturePadBlank = new SignaturePad(document.getElementById('signature-pad-blank'), {
backgroundColor: 'rgba(255, 255, 255, 0)',
penColor: 'rgb(0, 0, 0)'
});

var signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
backgroundColor: 'rgba(255, 255, 255, 0)',
penColor: 'rgb(0, 0, 0)'
});
var saveButton = document.getElementById('save');
var user_signature = document.getElementById('user_signature');
var signature_img = document.getElementById('signature_img');
var form = document.getElementById('form');
var undoButton = document.getElementById('undo');
var cancelButton = document.getElementById('clear');

cancelButton.addEventListener('click', function (event) {
    signaturePad.clear();
    var canvas = document.getElementById('signature-pad');
    ctx = canvas.getContext("2d");
    var background = new Image();
    background.src = "http://localhost:3000/van_picture.jpg";
    background.onload = function() {
    canvas.width = background.naturalWidth
    canvas.height = background.naturalHeight
    ctx.drawImage(background, 0, 0);
    };
    window.onresize = resizeCanvas;
    resizeCanvas();
    });

var user_signature_blank = document.getElementById('user_signature_blank');
var signature_blank = document.getElementById('signature_blank');
var cancelButtonBlank = document.getElementById('clear_blank');

cancelButtonBlank.addEventListener('click', function (event) {
    signaturePadBlank.clear();
    });

saveButton.addEventListener('click', function (event) {

    if (signaturePad.toData().length == 0 ) {
    alert("Please provide a signature on image");
    return false
    }
    else if(signaturePadBlank.toData().length == 0) {
      alert("Please provide a signature on blank");
      return false
      }
    else
    {
    var data = signaturePad.toDataURL('image/png');
    signature_img.value = signaturePad.toDataURL("image/png");
    var data_blank = signaturePadBlank.toDataURL('image/png');
    signature_blank.value = data_blank;
    form.submit();
    }
    });
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<br/>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<%= image_tag @user.signature_blank.url %>
<p>
<%= image_tag @user.signature_img.url %>
<!--
we can also show from raw base64 data
<img src="<%#= @user.signatures%>"/>
-->